apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eksdemo-cluster
  region: us-east-2

nodeGroups:
  - name: ng-1
    instanceType: t3a.medium
    desiredCapacity: 2
    ssh:
      publicKeyName: new-key
  - name: ng-2
    instanceType: t3a.small
    desiredCapacity: 2
    ssh:
      publicKeyName: new-key