apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: memory-autoscale-demo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nodejs-apps
  minReplicas: 10
  maxReplicas: 40
  metrics:
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 60