apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-cpu
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nodejs-apps
  minReplicas: 10
  maxReplicas: 50
  targetCPUUtilizationPercentage: 50